### ISSUE TITLE
triggering initial action in child component

### ISSUE THREAD

**Issue by stratospark** [stratospark/pux-elm-architecture#2]
@alexmingoia Any guidance on how to automatically send an action to a child component upon creation? https://github.com/stratospark/pux-elm-architecture/blob/master/ex7/src/Layout.purs#L41

I have a list of `RandomGif` components as children of the parent. When the parent `Create`s a new child, I want to trigger the `RandomGif.RequestMore` action, so that the random image automatically loads.

I've tried unsuccessfully to compose updates:

```
update Create state =
  let
    newGif = RandomGif.init state.topic
  in { state: state { gifList = snoc state.gifList { id: state.nextID, state: newGif }
                    , nextID = state.nextID + 1
                    , topic = "" }
     , effects: _.effects $ update (Modify state.nextID RandomGif.RequestMore) state }
```

Another approach would be to have `RandomGif.init` allow for effects, like in the elm example, but I am not sure if that is possible here.

Thanks so much, I really appreciate the help and all the great work on this awesome library!

**Comment by stratospark** [comment]
Fixed here: https://github.com/stratospark/pux-elm-architecture/commit/851e6273015665e1998dbc34ed3f5f539c875ab8. Though, wondering if there is something like `delay` built into the Aff library.

**Comment by alexmingoia** [comment]
You can wrap any value into the current monad context using `Prelude.pure`, (`Prelude.return` is another alias for the function, which is what Haskell calls it). So instead of writing your own `Aff` function you call `delay`, you could just write `return $ Modify state.nextID RandomGif.RequestMore`. That would be the idiomatic way to just return a value within the `Aff` monad.

If you actually want to delay by time - as in `setTimeout` - Aff does provide a function called [`later'`](https://pursuit.purescript.org/packages/purescript-aff/0.16.1/docs/Control.Monad.Aff#v:later%27) which can do that.

I hope that helps.

**Comment by alexmingoia** [comment]
For example, `Maybe` is a monoid. One way to wrap the value `a` in a maybe is to use the `Just` constructor: `Just a`. But since `Maybe` is monoidal (it implements the monad typeclasses), you can use `pure` (aka `return`): `return a` would wrap `a` in `Maybe`. `return` can be used on any type that implements the relevant typeclasses, including `Aff`.
